version: 1

defaults:
  working_dir: .
  stop_on_failure: true
  overlap: skip
  timezone: UTC

monitor:
  enabled: true
  endpoint: http://127.0.0.1:7410
  api_key: ""
  timeout_ms: 400
  heartbeat_seconds: 15
  buffer:
    max_events: 5000
    flush_interval_ms: 1000
    spool_file: .chief/telemetry_spool.jsonl

jobs:
  - name: sample-etl-pipeline
    enabled: true
    overlap: skip
    monitor:
      enabled: true
      check:
        enabled: true
        grace_seconds: 120
        alert_on_failure: true
        alert_on_miss: true
    schedule:
      frequency: interval
      every: 1m
    scripts:
      - path: workers/sample/extract_demo.py
        args:
          - --source
          - mock-orders-api
          - --records
          - "30"
          - --seed
          - "123"
          - --output
          - workers/sample/state/extracted_orders.json
        timeout: 120

      - path: workers/sample/transform_demo.py
        args: --input workers/sample/state/extracted_orders.json --output workers/sample/state/transformed_orders.json --min-order-total 20
        timeout: 120

      - path: workers/sample/load_demo.py
        args:
          - --input
          - workers/sample/state/transformed_orders.json
          - --history-output
          - workers/sample/state/load_history.jsonl
          - --warehouse
          - demo-local
          - --table
          - fact_sample_orders
          - --fail-if-empty
        timeout: 120

  - name: sample-quality-check
    enabled: true
    overlap: queue
    monitor:
      enabled: true
      check:
        enabled: true
        grace_seconds: 180
        alert_on_failure: true
        alert_on_miss: true
    schedule:
      frequency: interval
      every: 2m
    scripts:
      - path: workers/sample/quality_check_demo.py
        args:
          - --transformed-file
          - workers/sample/state/transformed_orders.json
          - --history-file
          - workers/sample/state/load_history.jsonl
          - --max-age-hours
          - "48"
          - --min-records
          - "1"
          - --warn-average-below
          - "30"
        timeout: 60
